# Generated by Django 2.1.2 on 2018-10-06 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.BigIntegerField()),
                ('type', models.CharField(blank=True, max_length=1023)),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=1023)),
                ('image', models.URLField()),
                ('video_class', models.CharField(blank=True, max_length=1023)),
                ('actor', models.CharField(blank=True, max_length=1023)),
                ('video', models.URLField()),
                ('duration', models.CharField(blank=True, max_length=255)),
                ('upload_date', models.CharField(blank=True, max_length=255)),
                ('content_location', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=1023)),
                ('image_cached', models.BooleanField(default=False)),
                ('image_update_time', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='image down job update time')),
                ('video_cached', models.BooleanField(default=False)),
                ('video_update_time', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0), verbose_name='video down job update time')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
